language: python
python: 3.8
branches: master

install:
  - pip install mkdocs-material
  - pip install mike

script:
  - mike install-extras
  - mike deploy 4.8.2 -p
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: master

