language: python
install:
  - pip install mkdocs-material
  - pip install mike
script:
  - mike install-extras
  - mike deploy ${TRAVIS_BRANCH#'release/'}
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: ${TRAVIS_BRANCH#'release/'}


